const langArr = {
    "unit": {
        "en": "My Support",
        "de": "Meine Unterstützung",
        "fr": "Mon soutien",
        "jp": "マイサポート",
        "kr": "내 지원",
        "ch": "我的支援",
        "ua": "Моя підтримка",
        "es": "Mi Soporte",
        "pt": "O meu apoio",
        "it": "Il mio supporto",
    },

    "title": {
        "en": "Have you account ?",
        "de": "Haben Sie ein Konto ?",
        "fr": "Avez-vous un compte ?",
        "jp": "アカウントをお持ちですか ？",
        "kr": "계정이 있으신가요 ?",
        "ch": "您有帳戶嗎 ？",
        "ua": "У вас є обліковий запис ?",
        "es": "¿Tienes cuenta ?",
        "pt": "Tem uma conta ?",
        "it": "Avete un conto ?",
    },

    "titler": {
        "en": "you dont have account ?",
        "de": "Sie haben kein Konto?",
        "fr": "Vous n'avez pas de compte ?",
        "jp": "アカウントをお持ちでないのですか？",
        "kr": "계정이 없으신가요?",
        "ch": "您沒有帳號？",
        "ua": "у вас немає облікового запису?",
        "es": "¿no tiene cuenta?",
        "pt": "não tem conta?",
        "it": "non hai un account?",
    },

    "log-in": {
        "en": "Join us",
        "de": "Mitmachen",
        "fr": "Rejoignez-nous",
        "jp": "参加する",
        "kr": "가입하기",
        "ch": "加入我們",
        "ua": "Приєднуйтесь до нас",
        "es": "Únete a nosotros",
        "pt": "Junte-se a nós",
        "it": "Unisciti a noi",
    },

    "sign-inl": {
        "en": "Sign in",
        "de": "Eintragen",
        "fr": "S'inscrire",
        "jp": "ログイン",
        "kr": "로그인",
        "ch": "登入",
        "ua": "Увійти",
        "es": "Iniciar sesión",
        "pt": "Iniciar sessão",
        "it": "Accedi",
    },

    "email": {
        "en": "Email",
        "de": "E-Mail",
        "fr": "Courriel",
        "jp": "電子メール",
        "kr": "이메일",
        "ch": "電子郵件",
        "ua": "Електронна пошта",
        "es": "Correo electrónico",
        "pt": "Correio eletrónico",
        "it": "Email",
    },

    "pass": {
        "en": "Password",
        "de": "Passwort",
        "fr": "Mot de passe",
        "jp": "パスワード",
        "kr": "비밀번호",
        "ch": "密碼",
        "ua": "Пароль",
        "es": "Contraseña",
        "pt": "Palavra-passe",
        "it": "Password",
    },

    "form-forgot": {
        "en": "Forgot your password?",
        "de": "Haben Sie Ihr Passwort vergessen?",
        "fr": "Vous avez oublié votre mot de passe ?",
        "jp": "パスワードをお忘れですか？",
        "kr": "비밀번호를 잊으셨나요?",
        "ch": "忘記密碼？",
        "ua": "Забули пароль?",
        "es": "¿Ha olvidado su contraseña?",
        "pt": "Esqueceu-se da sua palavra-passe?",
        "it": "Avete dimenticato la password?",
    },

    "Sign-up": {
        "en": "Sign up",
        "de": "Registrieren Sie sich",
        "fr": "S'inscrire",
        "jp": "登録する",
        "kr": "가입하기",
        "ch": "註冊",
        "ua": "Зареєструватися",
        "es": "Inscríbete",
        "pt": "Inscrever-se",
        "it": "Iscriviti",
    },

    "Name": {
        "en": "Name",
        "de": "Name",
        "fr": "Nom",
        "jp": "名称",
        "kr": "이름",
        "ch": "名稱",
        "ua": "Ім'я",
        "es": "Nombre",
        "pt": "Nome",
        "it": "Nome",
    },

    "Last-Name": {
        "en": "Last-Name",
        "de": "Nachname",
        "fr": "Nom de famille",
        "jp": "ラストネーム",
        "kr": "성",
        "ch": "姓氏",
        "ua": "Прізвище",
        "es": "Apellido",
        "pt": "Apelido",
        "it": "Cognome",
    },

    "Repeat-Password": {
        "en": "Repeat Password",
        "de": "Passwort wiederholen",
        "fr": "Répéter le mot de passe",
        "jp": "リピートパスワード",
        "kr": "비밀번호 반복",
        "ch": "重複密碼",
        "ua": "Повторити пароль",
        "es": "Repetir contraseña",
        "pt": "Repetir a palavra-passe",
        "it": "Ripetere la password",
    },

    "Your-gender": {
        "en": "Your gender",
        "de": "Ihr Geschlecht",
        "fr": "Votre sexe",
        "jp": "性別",
        "kr": "성별",
        "ch": "您的性別",
        "ua": "Ваша стать",
        "es": "Su sexo",
        "pt": "O seu género",
        "it": "Il tuo sesso",
    },
}